export const TYPES={
    GET_NOTES:"GET_ALL",
    ADD_NOTE:"ADD_NOTE",
    SET_EDIT_NOTE:"SET_EDIT_NOTE",
    UPDATE_NOTE:"UPDATE_NOTE",
    DELETE_NOTE:"DELETE_NOTE",
    FILTER_ARCHIVED:"FILTER_ARCHIVED",
    FILTER_ACTIVE:"FILTER_ACTIVE",
    ADD_CATEGORY:"ADD_CATEGORY",
    DELETE_CATEGORY:"DELETE_CATEGORY",
    SET_ERROR:"SET_ERROR",
    GET_CATEGORIES:"GET_CATEGORIES",
    CLEAN_FILTERS:"CLEAN_FILTERS",
    RESET_FORM:"RESET_FORM_VRS",
    SET_FORM_EDITABLE:'SET_FLAG_EDITABLE_FORM',
    RESET_FILTER_LIST:"RESET_FILTER_LIST",
    FILTER_CATEGORY:"FILTER_CATEGORY"
}